services:
    ngr-haproxy:
        image: danigaralfo/haproxy
        ports:
         - 8404:8404
         - 8080:443
        volumes:
         - ./HAProxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
        sysctls:
         - net.ipv4.ip_unprivileged_port_start=0
        
    ngr-mysql:
        image: mysql
        environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=bbdd
    
    ngr-rabbitmq:
        image: rabbitmq
        
    ngr-app-1:
        image: danigaralfo/ngr_web
        depends_on:
         - ngr-haproxy
         - ngr-mysql
         - ngr-intserv
         - ngr-rabbitmq
        restart: on-failure
    
    ngr-app-2:
        image: danigaralfo/ngr_web
        depends_on:
         - ngr-haproxy
         - ngr-mysql
         - ngr-intserv
         - ngr-rabbitmq
        restart: on-failure
        
    ngr-intserv:
        image: danigaralfo/ngr_intserv
        depends_on:
         - ngr-haproxy
         - ngr-mysql
         - ngr-rabbitmq
        restart: on-failure
    